"""RealSense camera utilities for EL-A3 SDK."""

from .camera import (
    CameraIntrinsics,
    ColorOrder,
    DepthUnit,
    PointCloud,
    RGBDFrame,
    RealSenseD435,
    import_pyrealsense2,
)
from .geometry import RigidTransform, rpy_to_matrix
from .book_spine_matcher import (
    BookSpineMatchConfig,
    BookSpineMatcher,
    BookSpineMatchResult,
    CenterAlignment,
    FeatureBackend,
    draw_book_spine_overlay,
    evaluate_center_alignment,
    load_template_image,
    match_target,
    match_with_fallback,
    polygon_to_bbox,
    polygon_to_roi,
    resize_keep_aspect,
    update_stable_state,
)
from .picker import (
    import_open3d,
    make_display_cloud,
    pick_point,
    pick_point_index,
    pick_target,
    point_cloud_to_open3d,
    prepare_view_cloud,
    save_selected_point,
    save_selected_target,
    save_point_cloud,
    SelectedPoint,
    SelectedTarget,
)

__all__ = [
    "CameraIntrinsics",
    "ColorOrder",
    "DepthUnit",
    "PointCloud",
    "RGBDFrame",
    "RealSenseD435",
    "RigidTransform",
    "BookSpineMatchConfig",
    "BookSpineMatcher",
    "BookSpineMatchResult",
    "CenterAlignment",
    "FeatureBackend",
    "import_open3d",
    "import_pyrealsense2",
    "draw_book_spine_overlay",
    "evaluate_center_alignment",
    "load_template_image",
    "make_display_cloud",
    "match_target",
    "match_with_fallback",
    "pick_point",
    "pick_point_index",
    "pick_target",
    "point_cloud_to_open3d",
    "prepare_view_cloud",
    "polygon_to_bbox",
    "polygon_to_roi",
    "resize_keep_aspect",
    "rpy_to_matrix",
    "save_selected_point",
    "save_selected_target",
    "save_point_cloud",
    "update_stable_state",
    "SelectedPoint",
    "SelectedTarget",
]
